<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lash.Users.Application\Lash.Users.Application.csproj" />
    <ProjectReference Include="..\Lash.Users.Domain\Lash.Users.Domain.csproj" />
  </ItemGroup>

</Project>
